# Generated by Django 3.1.2 on 2020-10-06 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20201005_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
