# Generated by Django 3.1.2 on 2020-10-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='todo',
        ),
        migrations.AddField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(to='todo.Category'),
        ),
    ]
