# Generated by Django 3.1.2 on 2020-10-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201007_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(related_name='todos', to='todo.Category'),
        ),
    ]
